# Generated by Django 4.2.9 on 2024-01-23 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=10, null=True)),
                ('mass', models.IntegerField(null=True)),
                ('engine_displacement', models.IntegerField(null=True)),
                ('power', models.IntegerField()),
                ('fuel', models.CharField(max_length=8, null=True)),
                ('manufacture_year', models.IntegerField(null=True)),
                ('owner_personal_code', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_number', models.UUIDField(default=uuid.uuid4, help_text='Unique policy number.', primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('policy_duration', models.IntegerField(default=365)),
                ('policy_type', models.CharField(max_length=255)),
                ('insurance_premium', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_risk', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_purpose', models.CharField(default='dwelling house', max_length=255)),
                ('construction', models.CharField(default='brick/concrete', max_length=255)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance.policy')),
                ('risks', models.ManyToManyField(help_text='Choose risks', related_name='property_policies', to='insurance.risk')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('personal_code', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Personal code')),
                ('birth_date', models.CharField(max_length=10, verbose_name='Birth date')),
                ('tel_num', models.CharField(max_length=14, null=True, verbose_name='Tel. No.')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='insurance.policyholder'),
        ),
        migrations.CreateModel(
            name='MTPLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_experience', models.IntegerField(default=10)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mtpl_policies', to='insurance.car')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('description_of_the_incident', models.CharField(max_length=1000)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='insurance.policy')),
            ],
        ),
        migrations.CreateModel(
            name='CASCOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_experience', models.IntegerField(default=10)),
                ('car_alarm', models.BooleanField(default=False)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casco_policies', to='insurance.car')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance.policy')),
            ],
        ),
    ]
